config/routes.rb
Rails.application.routes.draw do
 root 'hats#index'

  resources :hats

#     Prefix Verb   URI Pattern              Controller#Action
#     root GET    /                        hats#index
#     hats GET    /hats(.:format)          hats#index
#          POST   /hats(.:format)          hats#create
#  new_hat GET    /hats/new(.:format)      hats#new
# edit_hat GET    /hats/:id/edit(.:format) hats#edit
#      hat GET    /hats/:id(.:format)      hats#show
#          PATCH  /hats/:id(.:format)      hats#update
#          PUT    /hats/:id(.:format)      hats#update
#          DELETE /hats/:id(.:format)      hats#destroy

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/hat.rb
class Hat < ActiveRecord::Base

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hats_controller.rb
class HatsController < ApplicationController
  def index
    @hats = Hat.all
  end

  def new
    @hat = Hat.new
  end

  def show
    @hat = Hat.find_by_id(params[:id])
  end

  def create
    # hat_params = params.require(:hat).permit(:name, :description)
    @hat = Hat.new(hat_params)
   if @hat.save
      redirect_to hats_path, notice: "Hat created!"
   else
    render :new
   end 
    
  end

  def edit
    #this id comes from the browser url 
    @hat = Hat.find_by_id(params[:id])
  end

  def update
    @hat = Hat.find(params[:id])
    # hat = params.require(:hat).permit(:name, :description)
    if @hat.update(hat_params)
      redirect_to hats_path
    else
      # redirect_to edit_hat_path(@hat)
      #rendering maintains error messages
      render :edit
    end
  end

  def destroy
    @hat = Hat.find(params[:id])
      @hat.destroy
      redirect_to root_path
  end

  def hat_params
    params.require(:hat).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hat_helper.rb
module HatHelper
end

app/views/hats/edit.html.erb
<h2> Change your Hats</h2>

<%= form_for @hat do |f| %>
  <%= f.text_field :name %><br>

  <%= f.text_area :description %><br>

  <%= f.submit %>

<% end %>

app/views/hats/index.html.erb
<h1>All the Hats </h1>

<% @hats.each do |hat| %>
  <%=hat.name %><br>
  <%= hat.description %><br>
  <%= link_to 'Edit', edit_hat_path(hat) %> <br>

  <%= link_to 'Delete', hat_path(hat.id), method: :delete %>
  <!-- #link_to normally automatically to get requests so you have to chenge the #method to delete -->
   <br>



<% end %>
<br>
<%= link_to 'Make a New Hat', new_hat_path %>

app/views/hats/new.html.erb
# edit and new form are the same and can therefor use a partial

<h1>Create a Hat</h1>

<%= form_for @hat do |f| %>
  <%= f.text_field :name, placeholder: 'Hat Name' %><br>
  <%= f.text_area :description, placeholder: 'Describe your Hat!' %><br>

  <%= f.submit %>

<% end %>

<%= link_to 'Your Hats', hats_path %>

app/views/hats/show.html.erb
<h2>Your New Hat</h2>

<article>
    <header>
      <h2><%= @hat.name %></h2><br>
      <%= @hat.description %> <br>
    </header>
  </article>

  <%= link_to 'Your Hats', hats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HatApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>